---

- name: create install dir
  file:
    path: /usr/sap/install
    state: directory

- name: download sapcar
  get_url:
    url: "{{ url_sapcar }}"
    dest: /usr/sap/install/SAPCAR_LINUX.EXE
    mode: 0755
    timeout: "{{ url_timeout }}"
  register: result
  until: result is succeeded
  retries: "{{ url_retries_cnt }}"
  delay: "{{ url_retries_delay }}"